### ISSUE TITLE
User request: send BP_REQ_QUIT early in the Ogre client closing process.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#102]
User is reporting that closing Ogre client leaves the player online for a short period while Ogre shuts down, resulting in death in PvP scenarios. Possibly due to BP_REQ_QUIT not being sent early enough when Ogre client shuts down?

**Comment by cyberjunk** [comment]
I reviewed this. It seems the only cases OgreClient so far sends an explicit BP_REQ_QUIT would be (a) the chatcommand "quit" created by a user and (b) the server requesting a client to do so by that chatcommand.

Any other shutdown basically relies on the TCP connection getting terminated, specifically the TCP socket getting closed in ServerConnection.cs / end of ThreadProc(), once running loop finishes.
However that seemed pretty instant to me as well. Not sure how the old client handles this or if a BP_REQ_QUIT would be significantly faster than a socket close.

**Comment by skittles1** [comment]
This was caused by the server discarding BP_QUIT for that user due to flooding protection iirc and was fixed.
