### ISSUE TITLE
No sounds for special weapons

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#103]
Special Weapons like an hold-scim dont make a sound if it holds an enemy.

**Comment by cyberjunk** [comment]
Need to look at the playback data that is sent to the client. Likely just a small bug, wasn't able test so far.

**Comment by cyberjunk** [comment]
Was this may be some sort of outdated RSB problem?
Does the issue still exist?

**Comment by tyras2** [comment]
Still an issue

**Comment by skittles1** [comment]
This should be fixed now (was a kod issue, not an Ogre issue).
