### ISSUE TITLE
Stalls at the login screen?

### ISSUE THREAD

**Issue by Dreamo84** [cyberjunk/meridian59-dotnet#120]
So I downloaded the most up to date alpha client for 101/102 and whenever I try to login the connect and options buttons go grey and it just hangs indefinitely.

Any ideas? I didn't see any other issues like this.

**Comment by cyberjunk** [comment]
I haven't tested the vanilla variant on 101/102 for a long time and it's likely support might get dropped one day or there are some severe bugs. First make sure you have picked the correct download, the OpenMeridian version will not work on vanilla servers...

Then your issue sounds like you might be just using an outdated RSB file.

Try to replace the rsc0000-101.rsb in the OgreClient resource (it's either in the resources subfolder or in the resources/strings, not sure for the old version) with the one you can find in your updated legacy 101 client's resource folder (it's named rsc0000.rsb) there, so make sure to rename it correctly. It might be a good idea to copy over some other resources from the legacy 101 client as well, but this could also have a negative effect, I can't give you detailed advise on this right now.

As mentioned, please consider the 101 build as highly experimental and not made for productive use.
