### ISSUE TITLE
In-client updating?

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#121]
Another issue potentially requiring a large change... sorry :)

A recent problem we've been dealing with on 105/112 is that we can't push updates to the patcher and if it goes down, both servers would be suddenly unable to release any updates to players. In addition the patcher isn't working for some players (including one of the 112 devs) and they are currently having to request the zip download each update (for both clients).

We decided to restore the in-client updating ability to the classic client, but in a way that makes it compatible with the patcher (OpenMeridian105/Meridian59#91). The question remains of how to release Ogre client updates without requiring users to download the entire client again, and I was thinking that the same program (modified club.exe) could update Ogre also.

There's a lot of changes in that PR but the gist of it is the server sends a new protocol (AP_CLIENT_PATCH (12)) with data like where patchinfo.txt is hosted, where the client files are hosted, machine to connect to and the client then downloads patchinfo.txt, compares the hash of local club.exe (not pre-computed, major source of issues with patcher) with the patchinfo.txt one, and downloads club.exe if different. Then club.exe is launched, which checks and updates all other files.

I've written the club/clientpatch changes in a way that would work for Ogre client, all Ogre would need to do is respond to AP_CLIENT_PATCH by downloading patchinfo.txt and club via HTTP.

If you're okay with this change I could try and implement it though I'd probably need a bit of guidance (e.g. not really sure where this would fit in - it's probably a much larger code change in Ogre than in classic where it mainly hits server.c/download.c/transfer.c). FWIW a couple of us have been testing this on classic and it's pretty smooth from a user's point of view - server tells them to update, they click OK and the client updates/reopens without any further input.

**Comment by cyberjunk** [comment]
I see a point in this if the launcher is unsuitable.

This should also definitely go into the corelib as much as possible (to potentially allow bots to use it also etc.)

1) Implementing the AP_CLIENT_PATCH shouldn't be too difficult.
Add the enum value to Protocol.Enums.MessageTypeLoginMode.cs and create a GameMessage instance for it in Meridian59.Protocol.GameMessages.LoginMode according to all the other examples there and make sure to add your case to ExtractLoginModeMessage() in MessageController.cs. I'm not aware of the transferred data exactly but I'm sure you'll be able to implement the byte serializers and deserializers in the message class.

2) Download files from http-servers is easy, just use the internal .net classes like System.Net.Webclient. I guess this code could go into BaseClient.cs for example. So a handler for the AP_CLIENT_PATCH message could start downloads there.

3) Executing the club.exe shouldn't be difficult too ..

**Comment by skittles1** [comment]
PR #122
