### ISSUE TITLE
Client Commands

### ISSUE THREAD

**Issue by bs3n** [cyberjunk/meridian59-dotnet#13]
Playing on the german 115 Server, I can't make use of any client commands like for example "deposit" or "withdraw" at the bank. Neither the english nor german keywords are working, the client just ignores them.

**Comment by cyberjunk** [comment]
Thanks for your feedback.

1)
To put money into your bank account you have to offer the shillings to the NPC. Funny, but that's the way I learned the game back then... :-) But I will try to add the "deposit" chatcommand to next version.

2)
To take money out of your bank account you must use the chatcommand "withdraw", like "withdraw 100" for 100 shillings. I just verified this works on 101 for me, which means it should work on 115 as well. Can anyone else also confirm this does not work on 115?

**Comment by bs3n** [comment]
Thanks, depositing seems to work, but stupidly I haven't checked the withdraw command then :D

Still, I'm not able to close the client by command or broadcast messages (or maybe I'm just pretty dumb and failing all the commands).

**Comment by cyberjunk** [comment]
>> Still, I'm not able to close the client by command or broadcast messages (or maybe I'm just pretty dumb and failing all the commands).

Broadcast should be 'b' or 'broadcast', like 'b hello!'

Closing the client is currently only possible by either the window X in window mode, or ALT+F4.

**Comment by cyberjunk** [comment]
'deposit' command has been added to next version 1.0.3.6

**Comment by cyberjunk** [comment]
I'm closing this. Chat commands 'withdraw' and 'deposit' both work in current versions.
Additionally you can offer money to the banker by trade to deposit it.
