### ISSUE TITLE
Delete Mail

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#130]
Nvm there is no solution to delete a incoming mail

**Comment by cyberjunk** [comment]
True. I never noticed.
Until it's added, the mails can be deleted from the '/resources/mails/' folder.

**Comment by cyberjunk** [comment]
Fixed in https://github.com/cyberjunk/meridian59-dotnet/commit/95ca0d5b2f338f346fe95dbc5b911db2a5c12540

**Comment by cyberjunk** [comment]
Closing this, fix is live.
