### ISSUE TITLE
Text in Royal Ballot cannot be saved

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#137]
If you want to vote for an justicar and try to save the name in the ballot, there is no button to save

**Comment by cyberjunk** [comment]
This will be fixed in next version. See https://github.com/cyberjunk/meridian59-dotnet/commit/ddb81e2999b359d37be1e9a1b70b21e941a88048
There will be a new "OK" button in the object-details window in case the inscription is editable.

**Comment by tyras2** [comment]
Awesome work, thanks so much for all bug fixes so far

**Comment by cyberjunk** [comment]
Closing this, fix is live.
