### ISSUE TITLE
Room enchantment appears twice

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#142]
If you cast detect invisble, the room enchantment appears twice

**Comment by cyberjunk** [comment]
Thanks, I've noticed this bug, but I wasn't able to find a reproducable case.
This one should be good for fixing it...

**Comment by cyberjunk** [comment]
Fixed in https://github.com/cyberjunk/meridian59-dotnet/commit/bb4319fe73067ec15259fb3b7ea625c256b54ba5

**Comment by skittles1** [comment]
This fix is live now so this can probably be closed.

**Comment by cyberjunk** [comment]
Thanks.
