### ISSUE TITLE
Persistent window configuration upon logging.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#150]
It would be nice if the exact layout was persistent through logins. That includes, position, the information about whether a window is open or not and it's stack order (mostly chat appearing in front of the weapon overlay etc.) Maybe we should simply send the weapon and shield overlay to the background though.

**Comment by cyberjunk** [comment]
The Open/Close state is easy, just needs to be saved/loaded with the position/size values.
For Z-Ordering I can't say for sure right now.

**Comment by cyberjunk** [comment]
The open/closed state is easy.

1) Add boolean vars for visiblity here (for each of the Rects listed there)
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/OgreClientConfig.h#L222

2) Save visiblity state from UI objects to new booleans vars created in (1):
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/ControllerUI.cpp#L511

3) Apply visibility state by modifying this block (add second && configvar cond. to == playing)
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/ControllerUI.cpp#L583

4) Persistenly write config values to XML by modifying/adding here:
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/OgreClientConfig.cpp#L673

5) Read boolean visibility values from XML by modifying here:
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/OgreClientConfig.cpp#L242

**Comment by MorbusM59** [comment]
Solved.
