### ISSUE TITLE
Allow aliases to be dragged to the action bars as hotkeys.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#151]
Players also need the "hit enter" option, so they can disable it to use the hotkey for a banner. This would restore the last bit of old client functionality.

**Comment by cyberjunk** [comment]
Executing aliases using ActionButtons is technically possible to implement..

But we will need an icon in the alias-list which is draggable and which will be placed in the button slots, or better we need a couple of them to let players chose from.

However, there will likely be no "Hit enter" Option, because this is not the way aliases work in Ogre,
they in fact never get put into into any ui-element directly.

**Comment by MorbusM59** [comment]
Hmm, is there any other way we can allow players to use banners?

**Comment by cyberjunk** [comment]
>> Hmm, is there any other way we can allow players to use banners?

You can use banners without problems in Ogre already. It's like the millionth question about that :)
I really need to have a look at the old client, there must be something completely different...

In Ogre an alias is simply replaced by its defined value if a chat-input starts with it and before the command is actually parsed! You can also overwrite existing commands this way!

Assume you define an alias like this:
>>Alias: s
For: s ~B~r

Then afterwards whenever you type something like
>> s Hello guys!

It in fact will be turned into this before it's parsed/executed:
>> s ~B~r Hello guys!

So the default answer is:
>> Overwrite the the default say, tell, broadcast with aliases containing your banner. But of course you can also use other random aliases for that..

**Comment by MorbusM59** [comment]
Oh! I never realized that was the way aliases worked. I thought you couldn't type anything else, just call up the line by entering the alias and hitting enter.

**Comment by cyberjunk** [comment]
Closing this. Version 1.0.5.6 will allow users to assign aliases to action buttons by drag&drop.
