### ISSUE TITLE
Holding shift before typing in chat will multiply the first letter typed.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#157]
The amount of copies of the letter depends on how long the shift key has been held before typing the first letter. If you hold shift between 1 and 2 seconds in advance, you get 2 copies, if you hold it longer than that, you get 3 letters. I noticed because I tend to hold down the shift key with my pinky while trying to figure out how to start a sentence.

**Comment by cyberjunk** [comment]
Fixed in https://github.com/cyberjunk/meridian59-dotnet/commit/c8c580ae47885e2c6664f35a399c9bd37b858492
