### ISSUE TITLE
Monsters are flashing/invisible

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#16]
Tested some stuff on 104, and noticed, that monsters are sometimes flashing (skeletons in cv) or complete invisible (mostly if they are near a wall)

![invisible-monsters](https://cloud.githubusercontent.com/assets/12058341/7552057/2687399a-f6a1-11e4-8e0d-645af5172daa.jpg)

![image](https://cloud.githubusercontent.com/assets/12058341/7556380/33cdd406-f76e-11e4-9dd8-2569188d3d52.png)

**Comment by cyberjunk** [comment]
Closing this, haven't seen the issue for a long time...
It was likely fixed with the last adjustements on the 2d image objects.
