### ISSUE TITLE
List contents don't update properly when the container is dragged.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#161]
Results in list contents being visible outside the container.

**Comment by cyberjunk** [comment]
Most of the "not updated ui list" issues have been fixed in 1.0.4.8 and some remaining ones will be in 1.0.4.9.
I guess this can be closed then...

**Comment by cyberjunk** [comment]
Closing this here.
The lists are updating fine in latest versions.
Otherwise please re-open it again.
