### ISSUE TITLE
Some people find the right click behaviour of the client unintuitive.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#163]
It would be great if a right click always brought up the info screen of the item the right click is targeted at, even if it isn't a list item, but an object in the game world. (Right now, you have to target an object, then inspect.)

**Comment by cyberjunk** [comment]
You can assign the right click to any action you want...
But I agree that the "Inspect" would likely be a better default than "Attack".

**Comment by MorbusM59** [comment]
I have it set to inspect, however, you still have to target (left click) an object in the world, then right click, to bring up the info box. Ideally, the right click would both select and inspect an object. Actually, I don't see much of an issue with right click also selecting things before doing the action it is assgined to in general.

Maybe as an example: If I have a zombie targeted, then right click on a skeleton, the game will bring up the info for the zombie, not the skeleton, since the right click only triggers the inspect, not the select command.

**Comment by cyberjunk** [comment]
>> however, you still have to target (left click) an object in the world, then right click, to bring up the info box.

This sounds more like a bug. The right click is supposed to be able to execute an action on sometihng which is NOT your current target (e.g. without switching it).

**Comment by MorbusM59** [comment]
Interesting. I don't believe that has ever been the case in Ogre though.

**Comment by MorbusM59** [comment]
Working on this at the moment.

**Comment by MorbusM59** [comment]
Solved in #193 .
