### ISSUE TITLE
Corelib account types don't match server account types.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#165]
Corelib account types, from https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59/Common/Enums/AccountType.cs
```
    public enum AccountType : byte
    {
        USER = 0x00,
        ADMIN = 0x01,
        GUEST = 0x02
    }
```
Blakserv account types, from https://github.com/OpenMeridian105/Meridian59/blob/develop/blakserv/account.h#L16
```
enum { ACCOUNT_NORMAL = 0, ACCOUNT_ADMIN = 1, ACCOUNT_DM = 2, ACCOUNT_GUEST = 3};
```

When the server sends AP_LOGINOK (23) it sends its version of account type. Ogre uses the corelib version to determine whether a 'DM' type message will be sent to server and only allows it for admins, not DMs.

So the fix is obvious (add DM and check for it when sending 'DM' chat command) but I'm likely going to remove the guest related code from the server/kod entirely as it very unlikely to be used (we don't have a separate Hazar any more). Would you like me to remove the GUEST type from corelib also, and fix any references to it?

**Comment by cyberjunk** [comment]
I synced the account-type enum values here: https://github.com/cyberjunk/meridian59-dotnet/commit/3ad3999adf2f377af890d6ce442563432e461405

And I allow to send the 'dm', the 'go/getplayer/goplayer' and the admin-console command as well as open the Admin-UI also for account-type "DM" here: https://github.com/cyberjunk/meridian59-dotnet/commit/368b476c451a1291e944c2ec52f5b0e135bab411

**Comment by skittles1** [comment]
Fix is live now.
