### ISSUE TITLE
Players would like to have a big map (equivalent to the fullscreen map of the classic client)

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#167]
Not instead of the minimap, but in addition to it.

**Comment by MorbusM59** [comment]
Most people seem to be happy with the new scalable minimap though. Low priority I guess.

**Comment by cyberjunk** [comment]
I'm closing this due to the amount of other work left to do.
The resizable minimap should do just fine IMO.
