### ISSUE TITLE
UI windows disappearing after the game has been in the background for a while.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#173]
Every now and then, UI windows that were present before sending the app to the background will have vanished when the application is brought back into focus. E.g. if the inventory has vanished, a first click on the inventory button will not bring the window back (presumably because it is simply not displayed, but present), while the second click will bring back the window again.

This has also happened to me at the login and welcome screens, leaving an empty screen, save for the background scene. Since there is no button to bring the windows back, the only solution is closing and restarting the application.

**Comment by cyberjunk** [comment]
Should be fixed in next version.
See: https://github.com/cyberjunk/meridian59-dotnet/commit/5abc7fae2e8d66c95b1400d6e48838d75d479f31

**Comment by cyberjunk** [comment]
Closing this. Fix is live.
Bug was reproducable by using CTRL+ALT+DEL.
This case works fine now.
