### ISSUE TITLE
Camera rotation around character should probably be disabled while in first person.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#175]
Instead, a left click drag should have the same functionality as a right click drag in first person.

To an advanced user, that is a lack of flexibility, but it's quite minor. A lot of new Ogre users stumble across this though and complain about running in the wrong direction.

I wouldn't have posted this if it wasn't for the many people asking about it.

**Comment by cyberjunk** [comment]
Seemed like a good idea.

Implemented. See here:
https://github.com/cyberjunk/meridian59-dotnet/commit/676c987017341e30138e5eb06b3913f45f7d080f

**Comment by MorbusM59** [comment]
Yay, thanks! :D
