### ISSUE TITLE
Brax Levers Invisible

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#18]
I can't see the brax levers if i'm standing right in front of them. If you change the angle, they get visible though
![brax-levers-invisible](https://cloud.githubusercontent.com/assets/12058341/7552097/350c3e42-f6a2-11e4-8c60-0011a3577423.jpg)

**Comment by cyberjunk** [comment]
This was due to 2D object being 'pitched' to face the camera. The pitching moved them behind the walls. Version 1.0.3.8 and later won't pitch the 2D objects anymore and this issue will be solved.

**Comment by cyberjunk** [comment]
Fixed in 1.0.3.8 - closing ticket.
