### ISSUE TITLE
Sounds play at 100% volume for a fraction of a second before...

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#185]
...playing at the chosen value, even when volume is set to 100%.

That's highly annoying, since players are plagued by ear drum piercing sound fragments, unless they tune down their system volume, lowering the sound of all other sources as well.

**Comment by MorbusM59** [comment]
Has already been mentioned.

**Comment by cyberjunk** [comment]
Please let me know if this fixes the issue in next version:
https://github.com/cyberjunk/meridian59-dotnet/commit/5aa4d16875948e38030304806a5289d255010017
