### ISSUE TITLE
Loginscreen

### ISSUE THREAD

**Issue by cyberjunk** [cyberjunk/meridian59-dotnet#188]
Leaving this here for @MorbusM59 

The new Login screen doesn't seem very nicely placed for 1280x720 default resolution.
It's too close to the queen IMO, covering her even a bit..

<img src="http://i.imgur.com/flXhrGA.jpg"/>

I just compared the login to the old style, and I think:

a) The old 'embedded' style was not that bad at all?

b) If you add some sort of box around it, may be make it a bit more _sophisticated_?
It's just that plain rectangle... can do pretty much anything there, because it's a non resziable, not even movable element...

**Comment by MorbusM59** [comment]
Yeah, I'd like to tackle this together with a bit of a rework of the demo scene. I thought about having the login window as a solid element occupying the bottom 30% of the screen, with the demo scene occupying the top 70% and being realigned. We could have a nicely ornamented top border in that case.

Also, I'd like to have that slow pathing camera on the demo sceen. Maybe not necessarily Brax, but a brighter scene that shows off a bit more of the game. We could modify that scene depending on our current patch (if it brings new content and scenery).
