### ISSUE TITLE
Horizontal scrollbar appears when sizing a window with a listbox quickly.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#199]
If you drag the right border of a window to the left (making the window thinner) and do that quickly and don't stop at the left border, but keep dragging, a horizontal scrollbar will flicker up. If you drag off screen before releasing, the scrollbar will be persistent.

This only happens for listboxes, not editboxes or others. (buy, loot, contents, spells, skills etc.)

**Comment by cyberjunk** [comment]
Couldn't reproduce this anymore, guess it was fixed a while ago.
