### ISSUE TITLE
Persistent UI layout changes

### ISSUE THREAD

**Issue by cyberjunk** [cyberjunk/meridian59-dotnet#2]
The UI layout (location/size/visibility of internal game panels) is currently resetting with each restart of the game.

It can be manipulated persistently by editing the XML file Meridian59.layout, but should rather be saved and reloaded for each toon by the game itself.

**Comment by novemr** [comment]
i want that for the next release :D

**Comment by cyberjunk** [comment]
Closing this, implemented in 1.0.3.6
