### ISSUE TITLE
Chat Window: Cursor should be placed at the end when pressing "up"-arrow

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#20]
If you press UP Arrow, it will show your last commands, which is great, but the cursor is placed at the beginning of your command, which is not "best practice". the cursor should be placed at the end to make changes to your previous text entries easier.

**Comment by cyberjunk** [comment]
Fixed in 1.0.3.6

**Comment by cyberjunk** [comment]
Feature is live, closing this.
