### ISSUE TITLE
Inventory Slots seems to be limited

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#22]
i dont know if its relevant, but i can't see all my items on my local testserver, because i've got too many of them in my inventory. is there a limit of how many items can be displayed?

**Comment by cyberjunk** [comment]
Yes, the maximum amount of inventory slots is fixed in the UI.
It is 40 rows and 5 columns (=200 slots).

I believe this is sufficient (unless you are admin and just get any existing item).
But a dynamic inventory size would be an improvement...
