### ISSUE TITLE
"Reset viewing angle" Button

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#224]
Some feedback says, it would be nice to have a button that will reset the "viewing angle" to standart if someone messed it up too much, so there is no login/out needed.

Not sure how other games integrated a similar option?

**Comment by cyberjunk** [comment]
Not sure if I'm getting this right...

Are you referring to the case when players rotate the camera only by keeping the left mouse button pressed while moving the mouse to the left/right?

You can already sync the avatars direction back to the the camera by pressing the right mouse button.
Or you can keep them locked in sync by keeping the right mouse button pressed.
