### ISSUE TITLE
Hidden Bards/Guides are Visible

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#225]
Bards or Guides that are using "dm hidden" are still visible.

**Comment by skittles1** [comment]
I think the server should probably stop sending updates for hidden DMs to players, if Ogre is just using those then hiding them in the client isn't a foolproof solution.

**Comment by cyberjunk** [comment]
>> Bards or Guides that are using "dm hidden" are still visible.

Where are they shown?
Is the object renderer in the world?
Is the name shown in the world?
Are you referring to the "Entities" (map objects) list?

>> I think the server should probably stop sending updates for hidden DMs to players, if Ogre is just using those then hiding them in the client isn't a foolproof solution.

Agree. If you want to hide information from the client successfully, don't send it at all.

**Comment by skittles1** [comment]
This should be fixed now (server-side).
