### ISSUE TITLE
Hotkeys won't save properly when using "quit" instead of Xing the window.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#232]
Newly added hotkeys saved, switched hotkeys did not.

**Comment by cyberjunk** [comment]
Fixed in https://github.com/cyberjunk/meridian59-dotnet/commit/a7a6c3f1d435134e3133ac09def8d440adc1ae32

I think there might be a duplicate issue of this somewhere already..
