### ISSUE TITLE
Limit Zoom-Out

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#234]
Since you can zoom-out to very unattractive perspectives i would advise to limit the zoom-out to a compromise value.

**Comment by cyberjunk** [comment]
I think I want to have a slider in the options which controls the maximum zoom-out.
With a default that seems reasonable for presenting/trying out the game in reviews, but still gives the same power to casual players that cheaters might have by modifying the code to adjust the limit.

**Comment by SaschaOFC** [comment]
Agree with this kind of solution. I'm just remember an "Let's play" Video a player did some month ago and showed how - in his words - how stupid some perspectives look. Guess it would look much more professional if we implement something like above.

**Comment by tyras2** [comment]
Agree with this kind of solution. I'm just remember an "Let's play" Video a player did some month ago and showed how - in his words - how stupid some perspectives look. Guess it would look much more professional if we implement something like above.
