### ISSUE TITLE
Client crashing

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#236]
@cyberjunk After using spell "phase" to test the new overlay effect, my client crashed. After that i cant login, client crashing again after writing the first letter of my password.

**Comment by skittles1** [comment]
Sort of related to the phase overlay crash, if I cast phase and then try to quit from the chat window while phased, my client crashes with an InvalidCastException.

```
An unhandled exception of type 'System.InvalidCastException' occurred in Meridian59.dll

Additional information: Unable to cast object of type 'Meridian59.Protocol.GameMessages.GenericGameMessage' to type 'Meridian59.Protocol.GameMessages.EffectMessage'.
```
in DataController.cs line 1751

I assume there's somewhere that EffectMessage isn't handled yet so gets cast to GenericGameMessage? So far I've been unable to find it however. Also not sure what's causing the login issue.

**Comment by skittles1** [comment]
There are some other login issues that we can't reproduce (missing login box for some players, or just displaying the word 'Login' with no box) so I've reverted 105 to 1.0.4.8/ version 9014 for now.

**Comment by cyberjunk** [comment]
I can't reproduce any crash on Phase :-(

The crash exception Delerium posted is a very weird one that totally makes no sense to me right now.
It means that there is a Message instance processed in DataController, which has a BP_EFFECT id value on it, but is not a typed 'EffectMessage' class instance. 

This means when the message was parsed, it triggered the default case at one of these two places in MessageController.cs:

https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59/Protocol/MessageController/MessageController.cs#L300

https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59/Protocol/MessageController/MessageController.cs#L432

So it most likely sounds like a bad parser error, e.g. offset reading wrong data.
For instance a message which should've been read in Login Protocol-Mode, was read in Game Protocol-Mode. However, BP_EFFECT has the ID 70 and there is no AP_XXX message with that ID. So no Login Mode message was misinterpreted...

Please check your Meridian59.log next time, if there is a network parser error, there is a big log about it.

**Comment by cyberjunk** [comment]
Crash fixed here by making OgreClient more robust against unreadable 'GenericGameMessage':
https://github.com/cyberjunk/meridian59-dotnet/commit/a6584cd39d1f69dce8b60d30c40ed6b6f41a2af9

However, real cause of trouble is server-side (BP_ after BP_QUIT).
