### ISSUE TITLE
Default value for rotate speed should be max.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#241]
I don't really see why the default value should make players feel like steering a ship. Veterans will read the patch notes, change the values and be alright, but fresh players will probably figure that this is the way the game is played and be turned away right from the start. I'd strongly recommend starting players out with max rotate speed.

The slider could probably be narrowed to values that make a bit more sense as well. At the lowest speed setting, the camera will take about 15 seconds to stop rotating after the initial mouse movement has been registered (with MB held down). Since the scale isn't linear, I guess it doesn't matter all that much since everyone should be able to select their desired value anyway. I just feel it makes the client feel more alpha when crazy values are allowed. My recommendation: a linear scale from 1000ms to 0ms.

To be honest, I still don't really understand why rotate speed is required as a setting for mouse control in the first place. If I recall correctly, you introduced smooth camera movement to keep the camera from jerking all over the place when camera distance is temporarily reduced to avoid collision with geometry. That absolutely makes sense and I enjoy the smooth glide back to max distance. (I'd actually like a slider to control the glide speed.)

I don't really see, however, why anyone would need rotation smoothing (or laggy controls for that matter) when turning. If I move my mouse, I want my character to turn (by as much as I moved my mouse, adjusted by mouse sensitivity) and if I stop moving the mouse, I want my character to stop turning. Breaking that direct link between distance traveled on the mousepad and angular movement destroys the sense of control a player has of their character.

The only case for having the setting I can think of: It allows players to play with a mousepad the size of a matchbox. (Jerk mouse in a direction with button held down, wait for a second or two until your desired angle has been reached, release mouse button.)

I guess it's usually not a big problem to err on the side of too much customizability, but at the moment, the slider really feels a bit like a checkbox that allows you to boost speaker volume by 5000%. There might be fringe cases in which that might be desirable, but I'd still prefer not to have it as a setting.

Finally, if we stick with the current sliders, they should probably be labeled "mouse responsiveness" (instead of rotate speed) and "mouse sensitivity" (instead of rotate distance). Even though the current labels accurately reflect the way things are handled internally, they aren't really descriptive to a new player.

**Comment by cyberjunk** [comment]
Closing this.
The default mouse aim speed was increased from 45 to 75.
That is a much more reasonable default, final tweaking is up to the user.
