### ISSUE TITLE
Classic Client

### ISSUE THREAD

**Issue by ghost** [cyberjunk/meridian59-dotnet#250]
Hmm, sorry im new here.. but i want know why the OpenMeridian105-develop build, the most updated?
dont have a red dot with black borders when any mob target u example:
from meridiannext classic 105 client;
https://i.imgur.com/H5YpVA6.png
and the dev build:
https://i.imgur.com/Oo5MtSl.png
and in the dev build the mobs are not agressives, i tested with a normal and admin account ;-;
its a server side configuration ?
this project is so beautiful, despite never having played the game before, love this style of classic games like doom =3
sry, google translate lul

**Comment by cyberjunk** [comment]
Sorry, wrong place to ask for classic client issues.
This is only about OgreClient.
Also I don't really understand the problem, so I can't help.
