### ISSUE TITLE
Bug: Empty Inventory Slots can be dragged around / on items (which disappear)

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#26]
![image](https://cloud.githubusercontent.com/assets/12058341/7556276/5b4ce728-f76a-11e4-8fbe-84035a99ea01.png)

**Comment by cyberjunk** [comment]
This does not seem to happen for my current version anymore. I can not drop empoty slots on occupied ones. Version 1.0.3.5 also had a bug which crashed the client in case you tried to drop an item on an empty slot. I guess this issue here was fixed together with that.

**Comment by cyberjunk** [comment]
You won't be able to start dragging emtpy slots in 1.0.3.8 at all and in 1.0.3.7 dropping them somewhere should also not cause any harm like described here anymore. Closing tihs.
