### ISSUE TITLE
Enhancements / Bug Fixes

### ISSUE THREAD

**Issue by NHuebner1983** [cyberjunk/meridian59-dotnet#262]
Hi there :)

As you can see, Ogre Client is very popular. All of us opening issues is a good sign! (not being sarcastic either). So, thank you for making the client!!! `It's definitely the biggest enhancement to this game so far.`

I've been working on my own server & Ogre Client commits and noticed a few things... If I fix them before you, I will post back the fixed files to this issue or if you want I can send you a link to the commits. I don't really know how to do pull/push requests and all that. Plus I'm forked from someone who forked your master branch, so I don't think you want all of my commits or theirs.

 - **Main Ogre Window**
    - Pressing the Windows key on keyboard is captured by Ogre and eaten (not sure if this is on purpose, if it was, I'm ok with that to prevent accidental keystrokes).
        - This relates to the next item - Happy with either one fixed so I can debug the game easier, or work with my computer while I play the game in Windowed Mode.
    - The window is "On Top" of the auto-hide taskbar. So if I move my mouse below the window, the start menu does not activate. 
        - How I am currently handling this: I have to move the window to the left or the right and click outside of it, then click Start key.
        - or I am moving the window up a few pixels.  If you can have the window start a few pixels "higher up" or maybe 5 pixels less in total height, it would probably fix this completely.

 - **Login Screen**
    - First Time Show Login Box:    
         - Focus Password Box (cursor to type)
         - If no user text, focus User Box instead.
    - Any type of Failure which results in displaying the Login screen (bad pw, disconnect, etc):   Focus Password Box & Highlight Password.
         - If no User text, focus User Box instead.

 - **GUI** "would like to haves"
    -  GUI Windows in the Game which have a resize ability from the bottom should also have the same resize ability from the top. 
       - This would prevent having to drag the window up and then dragging it down to resize.
    - Ability to add "chat commands" as hotkeys like the classic client.
       - Perhaps when you type in a command in the chat input box, there can be a button to the right of the box that has a special icon, and the rollover text says "Create Hotkey with Chat Command" and then it allows you to select a hotkey to assign it to, which will place a "text-like" (true type font icon? idk) on the GUI Action Bar which you can use. Removing it would be as easy as right clicking it in the GUI Input in Preferences. 
       - or -- You can highlight the text, and drag it to a spot on your Action Bar (text from the input box).
       - This would be especially useful for DMs for events, etc.

 - **Targeting**
     - This might be something I only fix in my version because I'm not sure how other people like theirs... but for example, there's a few Targeting scenarios that can get out of hand really quick especially if you're in a sticky situation.
         - "Next Target" (tab I believe) - If your previous target is not within view, your next target should restart as the closest object in your view that can be targeted. 

 - **Game System - May not be related to Ogre**
    - *You can't see your selected target* message:
         - **Example:**   (bare with me so you understand the issue)
         - In an open room, I have 50 thrashers while testing on my Creator account.
         - I start illusionary firewall on top of the thrashers (maybe 2 firewalls)
         - The firewall appears in front of the thrashers, but they still get hit
         - While attacking, I will have random "You can't see your selected target" messages appear.
         - I believe this is due to the firewall interfering with "Is Object In Line of Sight" - not sure which function it is.
         - Perhaps when the attack routine is performed and it checks attack target visibility / distance it should ignore anything that isn't a wall. This means I could hit my monster through a tree, a wall of fire or any other obstruction that I can physically walk through.

I will post more as I get to them.

Thanks! :)

**Comment by SilenceM59** [comment]
Just adding a note here for myself and anyone else. In the OgreClient on most of the current forked versions like 112, you may notice your char faces weird directions when entering/leaving maps.  This is server side not Ogre. Has to do with the KOD files for each map which dictate your rotation. Just figured that out thinking I had a protocol issue.

**Comment by SilenceM59** [comment]
New feature added:

‘Change Password’.  I will have to post back a link to the commits but it works good.

**Comment by cyberjunk** [comment]
Sorry, so many ideas here, I really couldn't respond to all of them.
What I definitely like and just implemented is:

>> First Time Show Login Box:
    Focus Password Box (cursor to type)
    If no user text, focus User Box instead.

See here:
https://github.com/cyberjunk/meridian59-dotnet/commit/b37c181b76d9649914ea89c3eaa9c8ab635f284b

This will automatically put the focus/cursor to the password box if username is already set, or to the username, if it's still unknown etc. But not only for startup, but also if you switch the server in the combobox.

**Comment by NHuebner1983** [comment]
Thanks for getting back to me. I wasn't sure when you would be back so I put all of these in already. Glad you updated the main version.
