### ISSUE TITLE
Bug: Some sloped? Textures are distorted

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#27]
Happens on different places, like marion AH, Thrashers, Brax, etc.

![image](https://cloud.githubusercontent.com/assets/12058341/7556316/352f7ffe-f76c-11e4-9bb1-b95854918e80.png)

![image](https://cloud.githubusercontent.com/assets/12058341/7556323/5a053238-f76c-11e4-914c-41c25874d358.png)

**Comment by cyberjunk** [comment]
Should be fixed in 1.0.3.6

**Comment by cyberjunk** [comment]
Closing this, fixed in 1.0.3.6 which is online.
