### ISSUE TITLE
Room Bug: You'll get stuck in Brax Acient Building on the stairs

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#29]
Doesnt happen with vanilla client, so i guess its a problem with ogre? you have to blink to get out, or log into your vanilla client

![image](https://cloud.githubusercontent.com/assets/12058341/7556408/c9c15a5a-f76e-11e4-8a5b-a8d67f9028a4.png)

**Comment by cyberjunk** [comment]
Interesting, I guess denied movements are due to a collision being detected between your avatar and the ceiling there.

Question is: Why are you able to get up there in first place? :)

**Comment by cyberjunk** [comment]
This spot is fixed in 1.0.3.8
Closing ticket.
