### ISSUE TITLE
Inventory slots get reduced to half hight and apear misordered 

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#35]
By unknown cause the inventory bugs and some icons will apear with half height. This causes the inventory to appear as irregular grid. This problem apears together with loosing the upper half of the iventroy's first row. Scrolling the inventory by mouse solves the problems.

**Comment by cyberjunk** [comment]
Can confirm this, don't know the exact reason.
However the inventory is subject to change anyways, because it's kinda hacked together (like the fixed size etc.)

**Comment by novemr** [comment]
Dropping Items will cause that bug:
![image](https://cloud.githubusercontent.com/assets/12058341/8065857/7ba2fe68-0ee4-11e5-8bae-1d22d96ede9f.png)

**Comment by cyberjunk** [comment]
Misordering in case an item gets added or removed has been fixed in 1.0.3.6 / 1.0.3.7.
Misordering in case you resort items by drag'n'drop will be fixed in 1.0.3.8.
