### ISSUE TITLE
Not able to pickup loot selective

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#37]
Correct me if I'm wrong but it's a big problem that manual looting will always pick up cursed items while loot on stack cannot be selected as long as a monster corpse is on top.
There're often situations where it is required to loot some high value item very fast and then leave a map or room. Picking up equip like robes, shields and armor is a pain in the ass right now. 
A button to open a selective loot window would be awesome, quick and dirty idea is to exclude cursed stuff from looting when nothing is selected.

**Comment by cyberjunk** [comment]
Thanks, there was some discussion already how to deal with this. It's likely a loot window will be added like the old one. Until then you have 2 options:

1) Double-click the minimap and you'll get a list of objects in your room. You can also filter them there, so selecting the "Get" checkbox should very well outline you lootable magic items (for example).

2) It's possible to iterate your target over overlapping objects. Just make sure you keep your 'modifier' key pressed (by default: ALT), while you click on several times overlapping objects.

**Comment by AlgorithmsOfMathdestruction** [comment]
oh thanks that's good to know. Didn't recognize any of the options. Going to try that out :)

**Comment by AlgorithmsOfMathdestruction** [comment]
Well, using the right doubleclick on map works fine for me :) I like that magical items are colored red!

**Comment by tyras2** [comment]
FYI: The Pickup is one of the biggest issues for so many user on 112. Many asking for a better solution to get items and arent happy with the current one.

**Comment by cyberjunk** [comment]
Added a loot-selection popup in commit https://github.com/cyberjunk/meridian59-dotnet/commit/a142541e36e929809e4a1746543d15d882bafbf0 and others before

**Comment by cyberjunk** [comment]
Closins this. Loot system has been improved.
