### ISSUE TITLE
Trap - "Off the beaten path"

### ISSUE THREAD

**Issue by AlgorithmsOfMathdestruction** [cyberjunk/meridian59-dotnet#39]
When entering "off the beaten path" from "the kings way" taking the first dead end path you get trapped. You cannot get out of the dead end back on the "main path".

(99% sure about the map name, rechecking that tomorrow)

**Comment by cyberjunk** [comment]
If possible, please upload a screenshot of the place causing issues for you.
Also: Have you verified the old client behaves differently there?

**Comment by skittles1** [comment]
This is an issue with the room itself (passable flag set incorrectly in the last room update) but is fixed in the rooms pull request for the next update.

**Comment by AlgorithmsOfMathdestruction** [comment]
great :)

**Comment by cyberjunk** [comment]
Closing this here because it was probably a room issue or likely will be fixed with better movement collisions in 1.0.3.8
