### ISSUE TITLE
Dev Request: Show Room File? Name in "Room Objects" Window

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#44]
i found it hard to get the correct go rid_XYZ names for texturing, it would be really nice if the game would tell me the actual file/roo name of the current map. Maybe put it somewhere into the Rooms Objects Window?

![image](https://cloud.githubusercontent.com/assets/12058341/7684849/aa735614-fd89-11e4-8b6d-ad65de56fcdc.png)

**Comment by cyberjunk** [comment]
I'm not going to add this into the RoomObject list, because this information is useless to the players.
If you run a DEBUG (developer) build of the client and you'll get a dedicated new window full of information (including what you request.)
