### ISSUE TITLE
Login Screen: Wrong username/PW creates a standard alert box

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#48]
You gonna lose your focus on the game window + can't see any mouse cursor, so it's hard to hit "OK" (well, if you don't use ENTER)

The Error Notice should be ingame, not just a plain alert box

![image](https://cloud.githubusercontent.com/assets/12058341/7844399/6d30c6a0-04b0-11e5-8638-33955e83c6e0.png)

**Comment by cyberjunk** [comment]
Fixed in:
https://github.com/cyberjunk/meridian59-dotnet/pull/220
