### ISSUE TITLE
Login Screen: While connecting, the input fields should be inactive/greyed out

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#49]
Right now, you don't see if the client is trying to connect to the server, so you gonna hit enter a few times before the character selections pops up.

it would be nice, if we could get some kind of feedback from the client

![image](https://cloud.githubusercontent.com/assets/12058341/7844510/1a0c3a8a-04b1-11e5-8e38-bd1a131e795b.png)

![image](https://cloud.githubusercontent.com/assets/12058341/7844535/5cccef36-04b1-11e5-96e8-827a6872151e.png)

**Comment by cyberjunk** [comment]
Implemented in next 1.0.3.7

**Comment by cyberjunk** [comment]
Closing this, feature is live.
