### ISSUE TITLE
UI Problem: Double clicking some title bars results in strange behavior

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#52]
I dont know if we really need that feature (collapsing windows), but im not playing at low resolutions...

some Input fields are still visible after collapsing the "main window":

![image](https://cloud.githubusercontent.com/assets/12058341/7847210/7fb30c36-04c2-11e5-8ee6-71dfe71d181d.png)

**Comment by cyberjunk** [comment]
I don't think the collapse feature is needed.
It will be disabled for all windows by default in 1.0.3.7 - can reenable it for specific ones if needed.

**Comment by cyberjunk** [comment]
You can not collapse the windows in 1.0.3.7 anymore.
Closing this.
