### ISSUE TITLE
Login Screen is bugged if you get logged out

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#55]
If you log in with another client to the same account, the ogre login screen will be bugged (you'll get room stuff from the area you were logged out from)

![image](https://cloud.githubusercontent.com/assets/12058341/7890211/cc23e9ea-0644-11e5-884b-eee06687e7a8.png)

**Comment by cyberjunk** [comment]
Can confirm there is some issues with the loginscreen if you go back to it after login.

**Comment by cyberjunk** [comment]
Should be fixed in 1.0.4.4
