### ISSUE TITLE
Large Map

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#59]
I'm missing a nice feature of the old client: the large map

So, maybe you'll get a large (resizable) map if you hit M on keyboard? :)

![image](https://cloud.githubusercontent.com/assets/12058341/7918544/76fb6f92-0892-11e5-8b90-47227f760b16.png)

**Comment by AlleyCat1976** [comment]
The mini map works good, you can zoom in and out on it with your mouse. A large world map would be nice kind of like the one on Skyrim would be cooler

**Comment by cyberjunk** [comment]
I don't know Skyrim, so I don't know their map.
But I do see a reason why players want to have a bigger map...

I'm not yet sure whether it should be a dedicated second element like shown in the suggestion here - or just make the current minimap resizable?

**Comment by AlleyCat1976** [comment]
I would keep the mini map how it is personally. The large world map in Skyrim is basically a large overview with names of towns and a arrow icon on your location. It does have a teleport option but I wouldn't add that. Something like this 
https://www.google.ca/?gfe_rd=cr&ei=MSkBVZzwK4GYmAHg4ID4CA&gws_rd=ssl#q=skyrim+map+pic

**Comment by novemr** [comment]
im fine with both solutions (resizing or large additional map), but i'd prefer a squared map for the sake of not wasting much space :P

**Comment by AlleyCat1976** [comment]
Suggestion on map. I think personally its nice being able to completely zoom out and see the entire screen. Games I have played in the past have had this look. I understand there are a few things that can be a problem in pvp. Example, being able to target ppl from far away and well behind a wall. A simple fix that is already in the game. Range and hindered sight fixes that. I suppose to make it more clean looking a nice background to fill the void and a slight decrease in the zoom would be awesome. This way a tacky square map wont be needed. I also think the square map is a crutch for ppl when they are running for there life or dazzle blinded ect ect. Of course the zoom in and zoom out would have to be more decreased well in buildings so it wont look funny. Anyways, that's my 2 cents on zoom in zoom out and square maps

**Comment by tyras2** [comment]
I would love to see, when you can resize the map window

**Comment by cyberjunk** [comment]
Next OgreClient 1.0.4.4 will allow to smoothly resize the minimap in between 256x256 and 512x512.
It can be done by holding down the assigned 'Modifier' key (default: 'Alt') while the mouse is wheeled on the minimap. Also the incorrect draggable corners of the map will be fixed.

**Comment by cyberjunk** [comment]
I'm closing this.
The map is resizable since a while now.
Not exactly an additional big map as requested, but quite close to it.
