### ISSUE TITLE
Aliases: Can't copy/paste text, saving existing aliases aint possible without deleting them first (nt)

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#62]

**Comment by AlleyCat1976** [comment]
I noticed that also when I first decided to use the new client aswell. I guess this would be a request feature.

**Comment by cyberjunk** [comment]
I just added the copy & paste feature for the aliases, will be in next release.
Still have to have a look at the saving issue.

**Comment by cyberjunk** [comment]
Copy + Paste for alias keys and values was added in 1.0.3.7
Making changed aliases correctly work without restarting the game will be added in 1.0.3.8
