### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by AlleyCat1976** [cyberjunk/meridian59-dotnet#67]
Just curious if you have a time frame on a update ? I understand stuff takes time. I really enjoy your client so Im looking forward to see what has been added / fixed ect ect. BTW, that loot system that we spoke about. I noticed you did something there. Its not complete right ? Reason why I ask is because I did see that you added the right click feature but the trade can not be completed. I just figured you were still working on it =)

**Comment by cyberjunk** [comment]
I'm closing this, because it's not really a ticket.
If you want to chat about update schedule etc. come visit us in IRC :-)
