### ISSUE TITLE
No stat change dialog box in Ogre.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#68]
Sorry to open this rather than trying to code it myself (still learning C#) but players are trying to change stats with the Ogre client and as the dialog isn't in Ogre yet nothing happens.

**Comment by cyberjunk** [comment]
I'm closing this here, because someone else opened the same issue again and I responded there:
https://github.com/cyberjunk/meridian59-dotnet/issues/71
