### ISSUE TITLE
Ogre client news/mail subject length.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#69]
Old client is limited to a news/mail subject length of 50 characters, on 112 someone using the Ogre client was able to post a subject length greater than this which breaks the newsglobe for anyone on the old client.

I'm going to block subject lengths greater than 50 on the server, Ogre client should probably not send anything greater than that.

**Comment by cyberjunk** [comment]
Thanks, I've added the limit for the length on the Ogre UI level only, this should be enough to give users feedback when the limit is reached. Server then should not choke on invalid data, if anyone tries... , but seems you fixed that already...

https://github.com/cyberjunk/meridian59-dotnet/commit/330b75b60478aa949421ed27acca97fd0887249e

**Comment by cyberjunk** [comment]
This is part of 1.0.3.7, closing the ticket.
