### ISSUE TITLE
BGF editor doesn't load shrink factor and name on opening .bgf file.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#70]
Keep forgetting to bring this up in IRC, I've had a look at the code too but not sure how to fix the issue.

If you open a bgf, modify and save it again, the shrink factor and name are not saved. The workaround I'm using is to open the file, open the settings menu, then save and make sure the shrink factor and name are still present in the settings menu.

**Comment by cyberjunk** [comment]
Thanks. I have uploaded BgfEditor 1.0.9, please test.

**Comment by skittles1** [comment]
Looks like the problem is fixed, thank you :)
