### ISSUE TITLE
Trinkets can´t  be used in the new client

### ISSUE THREAD

**Issue by superflorik** [cyberjunk/meridian59-dotnet#71]
If you give the old man in marion a trinket , it´s happening nothing.

**Comment by superflorik** [comment]
what means enhancement?

**Comment by cyberjunk** [comment]
'Enhancement' is a classification for the ticket you have created.
It means you've made a valid request to improve OgreClient.

The stat-reset feature was added to the OpenMeridian variant of the game just a few weeks ago. While OgreClient 1.0.3.7 has already some interal stuff implemented for the Stat-Reset, the user-interface is still completely missing. So there is no real bug - it's just not integrated.

**Comment by superflorik** [comment]
okay , by the way do you have to download the new version of the client again or can you just patch it ?

**Comment by cyberjunk** [comment]
There is no update mechanism yet (hopefully will be integrated in the OpenMeridian Launcher soon). But right now each download/version is a full package - no patch/update.

**Comment by superflorik** [comment]
and how to do it?

**Comment by cyberjunk** [comment]
Trinkets can be used now in the latest release.
