### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#75]
Was helping a player install Ogre client today, had some issues come up. Player installed .NET 4.5.2 followed by the 1.0.3.7 Ogre client, then ran the x86 version and got:
```
The program cant start because MSVCP120.dll is missing from you computer. Try reinstalling the program to fix the problem.
```
Had the player download the VC++ 2013 redist from MS which fixed it, but then he got an error with missing irrklang.dll. Should either of these be packaged with the Ogre client?

**Comment by cyberjunk** [comment]
Both of these DLL files are shipped with the ZIP download in x86 AND x64 folders and therefore should be present out of box after extracting the ZIP, and without installing anything further.

irrklang.dll: The sound engine (http://ambiera.com/irrklang/)
MSVCP120.dll: Part of the VC+ 2013 redist package

**Comment by AlgorithmsOfMathdestruction** [comment]
The user isn't running Windows XP eh ?

**Comment by cyberjunk** [comment]
>> The user isn't running Windows XP eh ?

I don't think so.. he wouldn't be able to install .NET 4.5.2 at all (4.0 is last for XP).
Anyways - just to point this out here: Windows XP is not supported anymore.

**Comment by skittles1** [comment]
The user says he isn't very good with computers, I would say either one of your explanations could be the cause.
