### ISSUE TITLE
Safety state is not persistent

### ISSUE THREAD

**Issue by cyberjunk** [cyberjunk/meridian59-dotnet#76]
Toggling safety off will only last until next restart.

**Comment by MorbusM59** [comment]
Same goes for all other state settings (builder groups, reagent bag, spellpower display etc.)

**Comment by cyberjunk** [comment]
This is basically the same as here:
https://github.com/cyberjunk/meridian59-dotnet/issues/98

Since I responded there I'm going to close this one here. Issue should be fixed soon.
