### ISSUE TITLE
Startup crash - Windows 10 AMD FX-8150 GTX 960

### ISSUE THREAD

**Issue by nathanh0** [cyberjunk/meridian59-dotnet#78]
Hi :)

.NET 4.5.1+ already installed (came with OS) and tried to install again, wouldn't, said already installed.

Tried compatibility mode + Administrator (Windows 8).

I put the folder in Desktop as M59.

Tried both x86 and x64.

Any thoughts?

It stops on "Loading legacy resources"  for "CaelumLayeredClouds"

See tail end of the log below:

Thanks!

12:09:51: Loading resource group 'Caelum' - Resources: 1 World Geometry: 1
12:09:51: WARNING: material CaelumLayeredClouds has no supportable Techniques and will be blank. Explanation: 
Pass 0: Vertex program CaelumLayeredCloudsVP cannot be used - compile error.

12:09:51: WARNING: material Caelum/StarPoint has no supportable Techniques and will be blank. Explanation: 
Pass 0: Vertex program Caelum/StarPointVP cannot be used - compile error.

12:09:51: Texture: sun_disc.png: Loading 1 faces(PF_A8R8G8B8,128x128x1) with 0 generated mipmaps from Image. Internal format is PF_A8R8G8B8,128x128x1.
12:09:51: D3D9 : Loading 2D Texture, image name : 'moon_disc.dds' with 5 mip map levels
12:09:51: WARNING: material Caelum/PhaseMoon has no supportable Techniques and will be blank. Explanation: 
Pass 0: Fragment program Caelum/PhaseMoonFP cannot be used - compile error.

12:09:51: Texture: EarthClearSky2.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) with 0 generated mipmaps from Image. Internal format is PF_A8R8G8B8,64x64x1.
12:09:51: Finished loading resource group Caelum
12:09:51: Initialising resource group General
12:09:51: Parsing scripts for resource group General
12:09:51: Finished parsing scripts for resource group General
12:09:51: Creating resources for group General
12:09:51: All done
12:09:51: Caelum: Initialising Caelum system...
12:09:51: Caelum: Creating caelum sub-components.
12:09:51: Caelum: Creating CaelumSphericDome sphere mesh resource...
12:09:51: Caelum: generateSphericDome DONE
12:09:51: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "Caelum/PhaseMoon":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: Caelum: Failed to initialize moon: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "Caelum/PhaseMoon":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "Caelum/StarPoint":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: Caelum: Failed to initialize starfield: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "Caelum/StarPoint":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "CaelumLayeredClouds":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: Caelum: Failed to initialize clouds: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "CaelumLayeredClouds":  in Caelum at InternalUtilities.cpp (line 107)
12:09:51: Caelum: DONE initializing
12:09:51: CaelumSystem: Attached to viewport -1145960680 render target Meridian 59
12:09:51: OGRE EXCEPTION(-1:UnsupportedException): Can't load material "CaelumLayeredClouds":  in Caelum at InternalUtilities.cpp (line 107)

**Comment by cyberjunk** [comment]
Hi, none of the following steps should usually required, but please:

1) Try installing <a href="https://www.microsoft.com/en-US/download/details.aspx?id=35">DirectX 9.0 End-User Runtime</a>

Does not help ?

2) Try Installing <a href="https://www.microsoft.com/en-US/download/details.aspx?id=40784">Visual C++ Redistributable Packages for Visual Studio 2013</a>.
You might need the x64 to run OgreClient x64 and the x86 variant to run OgreClient x86.

Does not help ?

3) Try disabling the new sky by opening the configuration.xml (there is one for x86 and one for x64) and turn *false* into *true* in this line: *< disablenewsky value="false" />*

**Comment by nathanh0** [comment]
Item # 1 on your list was the fix, I am at the login screen without trying # 2 below.

My system came with Direct X 10.

Thanks! ☺

**Comment by cyberjunk** [comment]
Closing this since installing DX9 runtimes fixes the issue.
