### ISSUE TITLE
New client problem

### ISSUE THREAD

**Issue by m59mizt** [cyberjunk/meridian59-dotnet#82]
Hey,
Just downloaded new client I have all the requirements, I extracted the download to my desktop but whenever I try to run the 64 or 86 all I get is the windows loading circle and then the folder locks up and I have to go to the task manager to close it.

thanks in advance

**Comment by cyberjunk** [comment]
1) Have you tried installing all 3 dependencies listed here:
https://github.com/cyberjunk/meridian59-dotnet/wiki/Meridian59.Ogre.Client

2) Please upload/copy&paste the following three .log files from your x86 or x64 OgreClient directory:
Ogre.log
Meridian59.log 
CEGUI.log

3) What are your system specs (OS, CPU, GPU) ?

**Comment by m59mizt** [comment]
hi I managed to get it fixed my fire wall was blocking it but wasn't giving me any warning that it had blocked it. ive allowed it through the firewall and its all working thanks

**Comment by cyberjunk** [comment]
Closing this since issue was fixed
