### ISSUE TITLE
New client issue

### ISSUE THREAD

**Issue by Pegeta** [cyberjunk/meridian59-dotnet#83]
Tried both folders. Click the exe tries to load then i get a error message.

"Ogre3D client for Meridian 59 has stopped working a problem caused the program to stop working correctly. Please close the program."

Any ideas?

Thanks in advance

**Comment by cyberjunk** [comment]
Please have a look at the other ticket I just commented on.
https://github.com/cyberjunk/meridian59-dotnet/issues/82

If you can't fix the issue, please provide log files and specs.

**Comment by cyberjunk** [comment]
Closing this, there was no further reply.
