### ISSUE TITLE
Right click resets to hotkey 25 after restart.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#87]
Nothing to add.

**Comment by m59solo** [comment]
i can confirm that behavior

and an option to disable right click-mapping completely would be cool. Because its already used for freelook and walking. I often accidentally execute the mapped hotkey and have to left it unmapped because of this

**Comment by cyberjunk** [comment]
Reset after restart will be fixed in next version.

**Comment by cyberjunk** [comment]
Closing this, should be fixed in latest version (use OpenMeridian patcher).
