### ISSUE TITLE
Hotkeys are jumbled after using quit...

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#89]
...if they haven't been saved by closing the client via X first.

**Comment by cyberjunk** [comment]
Good catch. In fact the config never gets saved when just using "quit".
So it's likely that other changes (such as newly ignored players won't be saved too).

**Comment by cyberjunk** [comment]
Fixed since qutie some time, closing.

**Comment by cyberjunk** [comment]
Closing this, seems fixed. Can reassign hotkeys, use quit, login again and they're still as last edited.
