### ISSUE TITLE
Flickering buttons for game play settings...

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#91]
...will cause the client to spam on/off messages every now and then.

This usually happens after a server save wiped my settings and I'm trying to restore them. The spamming will continue forever and force a client restart.

**Comment by tyras2** [comment]
Got the same problem

**Comment by cyberjunk** [comment]
Guess this is linked to: https://github.com/cyberjunk/meridian59-dotnet/issues/98
Should be addressed by the same fix.

**Comment by cyberjunk** [comment]
Fixed a while ago
