### ISSUE TITLE
Change tags for hostile players in mini-map

### ISSUE THREAD

**Issue by JalenX** [cyberjunk/meridian59-dotnet#92]
Currently there is no way to discern monsters from hostile players in the mini-map.  The classic client uses a border in its tag to accomplish this.  The same thing would be nice for ogre as well.

**Comment by tyras2** [comment]
@JalenX @cyberjunk Yes, thats a real problem. I never see an enemy while building, because it looks like a monster. Should be improved very soon if its possible.

**Comment by cyberjunk** [comment]
I need to review all the changes Delerium did on the minimap. However it's not very difficult to adjust Ogre's minimap to draw two colord "pie" over another (inner/outer circle), instead of just one. I think this is what is required for most of the changes?

**Comment by cyberjunk** [comment]
Closing this.
Minimap behaviour and appearance was synced with classic client in 1.0.4.4
