### ISSUE TITLE
Display HP/Mana/Vigor

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#97]
In my opinion its isnt really good to see how many hp/mana or vigor you got. Maybe go back to this view?

<img width="275" alt="bildschirmfoto 2016-01-11 um 15 16 24" src="https://cloud.githubusercontent.com/assets/16498916/12235923/428c77fc-b877-11e5-9a76-613edc0bdb74.png">

**Comment by cyberjunk** [comment]
Hmmm IDK. Will keep it as an idea here. It wouldn't be too difficult to use a single color for these bars only.

**Comment by skittles1** [comment]
I think with the recent UI changes this is fixed, it's very easy to track remaining hp/mana/vigor now.

**Comment by cyberjunk** [comment]
Closing this. The UI for hp/mana/vigor bars have been drastically changed since the issue was opened.
