### ISSUE TITLE
Gameplay settings

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#98]
If there is an system safe, the gameplay settings (Grouping, Spellpower..) getting a reset and turned off.

**Comment by cyberjunk** [comment]
Should be fixed in this commit: https://github.com/cyberjunk/meridian59-dotnet/commit/4b8a3f90bcfdd20131a3b94c6031b1443063ef60

Leaving it open as long as it's not yet live.

**Comment by skittles1** [comment]
This is live in the patcher BTW

**Comment by cyberjunk** [comment]
Closing this. Fixed a while ago.
